"""Initial tables

Revision ID: 70c0605267a5
Revises: 
Create Date: 2025-06-28 11:31:33.095055

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '70c0605267a5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('parent_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['parent_id'], ['activity.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('building',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('address', sa.String(), nullable=True),
                    sa.Column('latitude', sa.Float(), nullable=False),
                    sa.Column('longitude', sa.Float(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_building_id'), 'building', ['id'], unique=False)
    op.create_table('organization',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('building_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['building_id'], ['building.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('organization_activities',
                    sa.Column('organization_id', sa.Integer(), nullable=True),
                    sa.Column('activity_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
                    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], )
                    )
    op.create_table('phone',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('number', sa.String(), nullable=False),
                    sa.Column('organization_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phone')
    op.drop_table('organization_activities')
    op.drop_table('organization')
    op.drop_index(op.f('ix_building_id'), table_name='building')
    op.drop_table('building')
    op.drop_table('activity')
    # ### end Alembic commands ###
